plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = "v${mod_version}-${minecraft_version}-fabric"
group = mod_group_id

base {
    archivesName = 'dont-punch-my-tacz'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Implementation-Title'  : project.base.archivesName.get(),
                'Implementation-Version': project.version,
        ])
    }
}
